
services:
  proxy-manager:
    container_name: proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=http://api.meicm.pt
        - VITE_REVERB_HOST=reverb.meicm.pt
        - VITE_REVERB_PORT=80
        - VITE_REVERB_SCHEME=http
        - VITE_REVERB_APP_KEY=my-key
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=:80
    depends_on:
      - db


  queue-worker:
    container_name: queue-worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: php artisan queue:work --verbose --tries=3 --timeout=60
    depends_on: [ db, redis, backend ]
    restart: unless-stopped

  reverb:
    container_name: reverb
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: php artisan reverb:start --host=0.0.0.0 --port=6001
    depends_on: [ db, redis, backend ]

  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./database/.env
    volumes:
      - db_data:/var/lib/mysql #nome do volume para guardar os dados
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  #Nome do script para crias as tabelas
    healthcheck: #para ver se a BD esta viva
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"

volumes:
  db_data: