
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=:80
    ports:
      - "8000:80"
    depends_on:
      - db


  queue-worker:
    container_name: queue-worker
    build: ./backend
    command: php artisan queue:work --verbose --tries=3 --timeout=60
    depends_on: [ db, redis ]
    restart: unless-stopped

  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./database/.env
    volumes:
      - db_data:/var/lib/mysql #nome do volume para guardar os dados
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  #Nome do script para crias as tabelas
    healthcheck: #para ver se a BD esta viva
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"

volumes:
  db_data: