CREATE DATABASE IF NOT EXISTS projectCN;
USE projectCN;

CREATE USER IF NOT EXISTS 'admin' IDENTIFIED BY 'root';
GRANT SELECT, INSERT, UPDATE, DELETE ON projet.* TO 'admin';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
     id INT PRIMARY KEY AUTO_INCREMENT,
     name VARCHAR(255) NOT NULL
);

INSERT INTO users (name) VALUES ('user1');